#######################
# Jenkins Build Options
#######################
# User guide for this file: https://github.com/samrocketman/jervis/wiki/User-Guide

language: groovy

#build library
script: ./gradlew clean check Jar

#whitelist git branches to build
branches:
  only:
    - master
    - jervis_simple

jenkins:
  pipeline_jenkinsfile: assets/Jenkinsfile
  collect:
    artifacts: build/libs/*.jar
    junit: build/test-results/*.xml
